import type { TableColumn } from "../types";

export const loansColumns: TableColumn[] = [
    {
        alignment: "text-end",
        badgeMore: 0,
        badgeType: "A",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "delinquency0Plus",
    },
    {
        alignment: "text-end",
        badgeMore: 0,
        badgeType: "B",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "delinquency30Plus",
    },
    {
        alignment: "text-end",
        badgeMore: 0,
        badgeType: "C",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "delinquency60Plus",
    },
    {
        alignment: "text-end",
        badgeMore: 0,
        badgeType: "E",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "delinquency90Plus",
    },
    {
        alignment: "text-end",
        badgeMore: 0,
        badgeType: "F",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "delinquencyRefinancing",
        tooltip: true,
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "status",
    },
    {
        alignment: "text-end",
        dataType: "amount",
        sortType: "numeric",
        sysName: "chbPayment",
        sysNameStatus: "chbPaymentStatus",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "amount",
        extended: true,
        sortType: "numeric",
        sysName: "flcPayment",
        sysNameStatus: "chbPaymentStatus",
        tooltip: true,
    },
    {
        alignment: "text-start",
        badgeEqual: "Microcredit",
        badgeType: "E",
        dataType: "text",
        sortType: "text",
        sysName: "loanType",
    },
    {
        alignment: "text-end",
        dataType: "amount",
        sortType: "numeric",
        sysName: "loanAmount",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "currency",
    },
    {
        alignment: "text-end",
        dataType: "amount",
        sortType: "numeric",
        sysName: "balanceAmount",
    },
    {
        alignment: "text-end",
        dataType: "amount",
        sortType: "numeric",
        sysName: "debtAmount",
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "unpaidPercent",
        sysNameStatus: "unpaidPercentStatus",
    },
    {
        alignment: "text-end",
        badgeMore: 0,
        badgeType: "E",
        dataType: "amount",
        sortType: "numeric",
        sysName: "delinquencyAmount",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "guarantee",
    },
    {
        alignment: "text-center",
        dataType: "date",
        sortType: "text",
        sysName: "creationDate",
    },
    {
        alignment: "text-center",
        dataType: "date",
        sortType: "text",
        sysName: "closeDate",
    },
    {
        alignment: "text-center",
        dataType: "date",
        sortType: "text",
        sysName: "lastUpdateDate",
        tooltip: true,
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "businessCategory",
    },
    {
        alignment: "text-end",
        dataType: "numericArray",
        sortType: "numericArray",
        sysName: "loanNumberNchb",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numericArray",
        sortType: "numericArray",
        sysName: "loanNumberUcb",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "paymentPeriod",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "monthsNumberSinceCreationDate",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "monthsNumberBeforeCloseDate",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "flcTaken",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "flcNchb",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "flcUcb",
        tooltip: true,
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        extended: true,
        sortType: "numeric",
        sysName: "contractPeriod",
        tooltip: true,
    },
];

export const personsColumns: TableColumn[] = [
    {
        alignment: "text-start",
        dataType: "text",
        sysName: "dataSource",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sysName: "clientName",
    },
    {
        alignment: "text-center",
        dataType: "date",
        sysName: "birthDate",
    },
    {
        alignment: "text-end",
        dataType: "text",
        sysName: "documentSeries",
    },
    {
        alignment: "text-end",
        dataType: "text",
        sysName: "documentNumber",
    },
    {
        alignment: "text-end",
        dataType: "date",
        sysName: "documentIssueDate",
    },
];

export const reportListColumns: TableColumn[] = [
    {
        alignment: "text-start",
        dataType: "numeric",
        sortType: "numeric",
        sysName: "appNumber",
    },
    {
        alignment: "text-center",
        dataType: "dateTime",
        sortType: "text",
        sysName: "appCreationDate",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        isLink: true,
        sysName: "clientName",
    },
    {
        alignment: "text-end",
        dataType: "numeric",
        sortType: "text",
        sysName: "documentSeries",
    },
    {
        alignment: "text-end",
        dataType: "text",
        sortType: "numeric",
        sysName: "documentNumber",
    },
];

export const userListColumns: TableColumn[] = [
    {
        alignment: "text-center",
        dataType: "dateTime",
        sortType: "text",
        sysName: "creationDate",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "firstName",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "lastName",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sortType: "text",
        sysName: "username",
    },
    {
        alignment: "text-start",
        dataType: "text",
        sysName: "roles",
    },
];
